# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://mirsking.com
date_format: "ordinal"
title: Mirsking's Blog
subtitle: "用心记录成长过程的点点滴滴！"
description: "Mirsking's Blog"
keywords: mirsking, Peng Wang
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/mirsking/mirsking.github.io

# ---------------- #
#      Author      #
# ---------------- #
author: Peng Wang (mirsking)
organization: Zhejiang University
organization_url: #https://www.sogou.com
location: Hangzhou, China
email: mirsking@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: mirsking 
facebook_username: mirsking 
zhihu_username: mirsking 
#twitter_username: mzlogin

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo, changyan
comments_provider: duoshuo
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: mirsking 
#disqus_username: mzlogin

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [C++, Python, Design Patterns]
#skill_mobile_app_keywords: [Android, Reverse Engineering]
skill_windows_keywords: [Qt]
popular_repos: ['mirsking.github.io', 'urdf_ws']
contribute_repos: ['zoharby/matconvnet', 'dawnos/PPD']
